[[cells]]
name = "ckb-cheque-script"
enable_type_id = true
location = { file = "build/release/ckb-cheque-script" }

# reference to on-chain cells
[[cells]]
name = "secp256k1_data"
enable_type_id = false
location = { tx_hash = "0xf8de3bb47d055cdf460d93a2a6e1b05f7432f9777c8c474abf4eec1d4aee5d37", index = 3 } 

[[cells]]
name = "secp256k1_blake2b_sighash_all_dual"
enable_type_id = false
location = { file = "ckb-miscellaneous-scripts/build/secp256k1_blake2b_sighash_all_dual" }

# Dep group cells
[[dep_groups]]
name = "dep_group"
cells = [
  "ckb-cheque-script",
  "secp256k1_data",
  "secp256k1_blake2b_sighash_all_dual"
]

# Replace with your own lock if you want to unlock deployed cells.
# For example the secp256k1 lock
[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x0000000000000000000000000000000000000000"
hash_type = "type"

